# Generated by Django 4.0.3 on 2022-10-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='MyModel1',
        ),
    ]
