# Generated by Django 4.0.3 on 2022-10-19 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_1', '0003_rename_char_val_mymodel1_charv_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel1',
            new_name='MyFirstTable',
        ),
    ]
