# Generated by Django 4.0.3 on 2022-10-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_1', '0005_mysecondtable_alter_myfirsttable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyThirdTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'MySecondTable',
            },
        ),
        migrations.RenameField(
            model_name='myfirsttable',
            old_name='fork',
            new_name='many_to_one',
        ),
        migrations.AddField(
            model_name='myfirsttable',
            name='many_to_many',
            field=models.ManyToManyField(to='my_app_1.mythirdtable'),
        ),
    ]
