# Generated by Django 4.0.3 on 2022-10-19 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_1', '0006_mythirdtable_rename_fork_myfirsttable_many_to_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mythirdtable',
            options={'verbose_name_plural': 'MyThirdTable'},
        ),
    ]
