# Generated by Django 4.0.6 on 2022-10-19 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app_1', '0007_alter_mythirdtable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFourthTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'MyFourthTable',
            },
        ),
        migrations.AddField(
            model_name='myfirsttable',
            name='one_to_one',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app_1.myfourthtable'),
        ),
    ]
