version: '3.1'

services:
  python:
    image: python
    container_name: python
    volumes:
      - ./src:/app
    working_dir: /app
    command: /bin/bash -c "pip install -r requirements.txt && python3 ./main.py && echo 'Main script finished!'"
    tty: true